add poetry
QuantumBA/pyverless pull request #4
Opened 2021-11-05 17:48 UTC by RafaOp2Aim

add poetry to simplify maintenance and publication of the library

2021-11-05 18:22 UTC, stradivari96 requested changes
También aprovecharía para quitar lo que tiene que ver con lo anterior:
1. borrar carpeta requirements
2. eliminar `.travis.yml` (ya se usa github actions)
3. utilizar poetry en github actions ([ejemplo](https://github.com/stradivari96/modern-python-template/blob/main/.github/workflows/main.yml))
4. eliminar `manifest.in` y `setup.py`

2021-11-05 18:22 UTC, stradivari96 commented on .gitignore
> +poetry.lock
Generalmente el `poetry.lock` se debería commitear

2021-11-10 10:51 UTC, stradivari96 commented
actualiza las versiones de los dev dependencies

2021-11-10 10:53 UTC, RafaOp2Aim commented
si, estaba viendo que podía ser problema de la imagen, pero no había caído en la versión de ipdb

2021-11-10 10:55 UTC, RafaOp2Aim commented on .gitignore
> +poetry.lock
cuando lo haces para una librería no es necesario subir el archivo

2021-11-10 10:57 UTC, RafaOp2Aim commented
He actualizado los actions, faltaría modificarlos para subir automáticamente la librería al pip de desarrollo y el de producción en los push a develop y master, pero eso prefiero hacerlo en una PR a parte. No quiero hacer tanto cambio en una sola PR

2021-11-11 13:49 UTC, Axomme87 approved these changes

2021-11-15 12:14 UTC, merged